import { useState } from 'react';
import { formTemplates, blankTemplate, type FormTemplate } from '../templates';

// Printable, fill-in-the-blanks form sheet.  Intentional blanks + dotted
// fill-lines mean the officer prints the sheet and writes the values by
// hand.  Print is scoped with @media print so only the sheet is sent to
// the printer (see styles.css `.tmpl-sheet` / `.tmpl-print`).

function Sheet({ tmpl }: { tmpl: FormTemplate }) {
  const today = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
  return (
    <div className="tmpl-sheet">
      <div className="tmpl-sheet-head">
        <div className="tmpl-crest" aria-hidden="true">HP</div>
        <div className="tmpl-sheet-title">
          <div className="tmpl-org">HARYANA POLICE · DIGITAL RECORDS</div>
          <h2>{tmpl.name}</h2>
          <div className="tmpl-sheet-sub">{tmpl.sub}</div>
        </div>
      </div>

      <div className="tmpl-sheet-meta">
        <span>Malkhana Register</span>
        <span>Station: ______________________</span>
        <span>Date: {today}</span>
      </div>

      <div className="tmpl-fields">
        {tmpl.fields.map(f => (
          <div className={`tmpl-field${f.type === 'textarea' ? ' ta' : ''}`} key={f.key}>
            <div className="tmpl-field-label">
              {f.label}
              {f.hint && <span className="tmpl-hint">({f.hint})</span>}
            </div>
            {f.type === 'textarea'
              ? <div className="tmpl-line tall" />
              : <div className="tmpl-line" />}
          </div>
        ))}
      </div>

      <div className="tmpl-sign">
        <div className="tmpl-sign-box">
          <div className="tmpl-line" />
          <div className="tmpl-sign-cap">Signature — Malkhana In-charge</div>
        </div>
        <div className="tmpl-sign-box">
          <div className="tmpl-line" />
          <div className="tmpl-sign-cap">Signature — SHO / Officer</div>
        </div>
      </div>

      <div className="tmpl-foot">
        Generated by e-Malkhana · Haryana Police · this sheet is a blank template for manual entry
      </div>
    </div>
  );
}

export function Templates() {
  const [active, setActive] = useState<FormTemplate | null>(null);

  // Custom blank builder
  const [showBuilder, setShowBuilder] = useState(false);
  const [docName, setDocName] = useState('');
  const [fieldText, setFieldText] = useState('');

  function build() {
    const labels = fieldText.split('\n');
    const tmpl = blankTemplate(docName, labels);
    if (tmpl.fields.length === 0) return;
    setActive(tmpl);
    setShowBuilder(false);
  }

  return (
    <div className="view">
      <div className="page-head">
        <div>
          <h1>Templates</h1>
          <div className="sub">Generate blank, fill-in-the-blanks forms for case property & Malkhana registers, then print.</div>
        </div>
        <div className="btn-row">
          <button className="btn ghost" onClick={() => setShowBuilder(true)}>+ New Blank Form</button>
        </div>
      </div>

      {!active && (
        <div className="tmpl-grid">
          {formTemplates.map(t => (
            <div className="tmpl-card" key={t.id}>
              <div className="tmpl-card-name">{t.name}</div>
              <div className="tmpl-card-sub">{t.sub}</div>
              <div className="tmpl-card-meta">{t.fields.length} fields</div>
              <div className="tmpl-card-actions">
                <button className="btn small" onClick={() => setActive(t)}>Open</button>
              </div>
            </div>
          ))}
        </div>
      )}

      {active && (
        <div className="tmpl-preview">
          <div className="tmpl-preview-bar">
            <button className="btn ghost small" onClick={() => setActive(null)}>← All templates</button>
            <button
              className="btn small"
              onClick={() => window.print()}
            >🖨 Print blank form</button>
          </div>
          <Sheet tmpl={active} />
        </div>
      )}

      {/* Custom blank-form builder */}
      <div className={`overlay${showBuilder ? ' open' : ''}`} onClick={e => {
        if (e.target === e.currentTarget) setShowBuilder(false);
      }}>
        <div className="form-card">
          <button type="button" className="tag-close" onClick={() => setShowBuilder(false)} aria-label="Close">✕</button>
          <h3>New Blank Form</h3>
          <div className="sub">Add your own field names — each becomes a blank fill-in line. Type one field per line.</div>
          <div className="form-grid">
            <label className="full">
              Document title
              <input
                value={docName}
                onChange={e => setDocName(e.target.value)}
                placeholder="e.g. Vehicle Seizure Form"
              />
            </label>
            <label className="full">
              Fields (one per line)
              <textarea
                value={fieldText}
                onChange={e => setFieldText(e.target.value)}
                placeholder={'FIR / DD No.\nDate\nVehicle No.\nEngine No.\nChassis No.\nSeized From'}
                style={{ minHeight: 140 }}
              />
            </label>
          </div>
          <div className="form-actions">
            <button type="button" className="btn ghost" onClick={() => setShowBuilder(false)}>Cancel</button>
            <button type="button" className="btn" disabled={!fieldText.trim()} onClick={build}>
              Create blank template
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
