import { useEffect, useMemo, useState } from 'react';
import { api } from '../api';
import {
  formTemplates,
  blankTemplate,
  firValues,
  type FormTemplate,
  type DocField,
  type LetterParagraph,
  type LetterHead,
} from '../templates';
import type { CaseRow } from '../types';

// Printable, fill-in-the-blanks form sheet.  Intentional blanks + dotted
// fill-lines mean the officer prints the sheet and writes the values by
// hand.  Print is scoped with @media print so only the sheet is sent to
// the printer (see styles.css `.tmpl-sheet` / `.tmpl-print`).
//
// Two flavours:
//   kind 'form'   — labelled fields rendered as dotted fill-lines.
//   kind 'letter' — prose performa; paragraphs containing {{key}} tokens are
//                   merged with the officer's filled values and rendered as a
//                   letter body with inline gaps where a value is still blank.

function Sheet({ tmpl, values }: { tmpl: FormTemplate; values: Record<string, string> }) {
  const today = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
  const kind = tmpl.kind || 'form';
  const isHindi = !!tmpl.hindi;

  return (
    <div className={`tmpl-sheet${isHindi ? ' hindi' : ''}`}>
      <div className="tmpl-sheet-head">
        <div className="tmpl-crest" aria-hidden="true">HP</div>
        <div className="tmpl-sheet-title">
          <div className="tmpl-org">HARYANA POLICE · DIGITAL RECORDS</div>
          <h2>{tmpl.name}</h2>
          <div className="tmpl-sheet-sub">{tmpl.sub}</div>
        </div>
      </div>

      <div className="tmpl-sheet-meta">
        <span>Malkhana Register</span>
        <span>Station: ______________________</span>
        <span>Date: {today}</span>
      </div>

      {kind === 'letter'
        ? <LetterBody paragraphs={tmpl.paragraphs || []} values={values} letterhead={tmpl.letterhead} />
        : <FormFields fields={tmpl.fields} values={values} />}

      <div className="tmpl-sign">
        <div className="tmpl-sign-box">
          <div className="tmpl-line" />
          <div className="tmpl-sign-cap">Signature — Malkhana In-charge</div>
        </div>
        <div className="tmpl-sign-box">
          <div className="tmpl-line" />
          <div className="tmpl-sign-cap">Signature — SHO / Officer</div>
        </div>
      </div>

      <div className="tmpl-foot">
        Generated by e-Malkhana · Haryana Police · this sheet is a blank template for manual entry
      </div>
    </div>
  );
}

// Render a prose performa.  Static paragraphs print as-is; paragraphs flagged
// `blank` are merged with the officer's values: any {{key}} that has a value
// is shown inline (bold), any still-empty key becomes a dotted "____" gap.
function LetterBody({ paragraphs, values, letterhead }: {
  paragraphs: LetterParagraph[];
  values: Record<string, string>;
  letterhead?: LetterHead;
}) {
  return (
    <div className="tmpl-letter">
      {letterhead && (
        <div className="tmpl-letterhead">
          <div className="tmpl-lh-row tmpl-lh-top">
            <span className="tmpl-lh-left">{letterhead.station}</span>
            <span className="tmpl-lh-right">{letterhead.district}</span>
          </div>
          {letterhead.service && <div className="tmpl-lh-service">{letterhead.service}</div>}
          <div className="tmpl-lh-authority">{letterhead.authority}</div>
          <div className="tmpl-lh-city">{letterhead.city}</div>
        </div>
      )}
      {paragraphs.map((p, i) => {
        if (!p.blank) {
          return <p key={i} className="tmpl-para">{p.text}</p>;
        }
        // Merge tokens into React nodes so filled values render inline and
        // missing ones render as a dotted gap.
        const nodes: React.ReactNode[] = [];
        const re = /\{\{\s*([\w]+)\s*\}\}/g;
        let last = 0; let m: RegExpExecArray | null;
        while ((m = re.exec(p.text)) !== null) {
          if (m.index > last) nodes.push(p.text.slice(last, m.index));
          const v = (values[m[1]] || '').trim();
          nodes.push(
            v
              ? <span key={m[1]} className="tmpl-fill">{v}</span>
              : <span key={m[1]} className="tmpl-gap" />,
          );
          last = m.index + m[0].length;
        }
        if (last < p.text.length) nodes.push(p.text.slice(last));
        return <p key={i} className="tmpl-para">{nodes}</p>;
      })}
    </div>
  );
}

function FormFields({ fields, values }: {
  fields: DocField[];
  values: Record<string, string>;
}) {
  return (
    <div className="tmpl-fields">
      {fields.map(f => {
        const v = (values[f.key] || '').trim();
        const cls = `tmpl-field${f.type === 'textarea' ? ' ta' : ''}`;
        return (
          <div className={cls} key={f.key}>
            <div className="tmpl-field-label">
              {f.label}
              {f.hint && <span className="tmpl-hint">({f.hint})</span>}
            </div>
            {f.type === 'textarea'
              ? <div className={`tmpl-line tall${v ? ' filled' : ''}`}>{v}</div>
              : <div className={`tmpl-line${v ? ' filled' : ''}`}>{v}</div>}
          </div>
        );
      })}
    </div>
  );
}

export function Templates() {
  const [active, setActive] = useState<FormTemplate | null>(null);

  // Custom blank builder
  const [showBuilder, setShowBuilder] = useState(false);
  const [docName, setDocName] = useState('');
  const [fieldText, setFieldText] = useState('');

  // --- FIR auto-fill ---
  const [cases, setCases] = useState<CaseRow[]>([]);
  const [casesErr, setCasesErr] = useState('');
  const [selectedFir, setSelectedFir] = useState('');
  const [manual, setManual] = useState<Record<string, string>>({});

  // Load the case list once when a template is opened (so the FIR dropdown
  // can be populated).  Failures are non-fatal — the dropdown just stays
  // empty and the officer can still type values by hand.
  useEffect(() => {
    if (!active) return;
    let alive = true;
    setCases([]); setCasesErr(''); setSelectedFir(''); setManual({});
    api.cases()
      .then(list => { if (alive) setCases(list); })
      .catch(e => { if (alive) setCasesErr(String(e?.message || e)); });
    return () => { alive = false; };
  }, [active]);

  // Final values = prefill-from-FIR (if a FIR is chosen) merged over any
  // values the officer typed manually.  Manual edits always win.
  const values = useMemo<Record<string, string>>(() => {
    if (!active) return {};
    const base: Record<string, string> = {};
    if (selectedFir) {
      const c = cases.find(c => c.id === selectedFir);
      if (c) Object.assign(base, firValues(c));
    }
    return { ...base, ...manual };
  }, [active, selectedFir, cases, manual]);

  function onFirChange(id: string) {
    setSelectedFir(id);
    // Prefilling from a FIR resets any manual edits that came from a
    // previous selection so we don't carry stale values across cases.
    setManual({});
  }
  function onManual(key: string, val: string) {
    setManual(prev => ({ ...prev, [key]: val }));
  }

  function build() {
    const labels = fieldText.split('\n');
    const tmpl = blankTemplate(docName, labels);
    if (tmpl.fields.length === 0) return;
    setActive(tmpl);
    setShowBuilder(false);
  }

  // Fit the printable sheet onto ONE A4 page.  Measured from the sheet's
  // natural (unzoomed) height against the page's printable height; if it
  // overflows we scale it down via the `--sheet-zoom` CSS var so it never
  // spills onto a second page.  Restore zoom after printing.
  useEffect(() => {
    function fitToPage() {
      const sheet = document.querySelector<HTMLElement>('.tmpl-sheet');
      if (!sheet) return;
      sheet.style.zoom = '';                 // measure natural size
      const natural = sheet.getBoundingClientRect().height;
      // A4 portrait printable height = 297mm − 12mm top − 12mm bottom margins.
      // px @96dpi => 1mm = 96/25.4 = 3.7795px.
      const pageH = (297 - 12 - 12) * 3.7795;
      // Never spill to a 2nd page: scale down as far as needed (no floor) and
      // leave a 3% safety margin so rounding can't push it over.
      const scale = natural > pageH ? Math.min(1, (pageH / natural) * 0.97) : 1;
      sheet.style.setProperty('--sheet-zoom', String(scale));
      sheet.style.zoom = String(scale);
    }
    function resetZoom() {
      const sheet = document.querySelector<HTMLElement>('.tmpl-sheet');
      if (sheet) {
        sheet.style.zoom = '';
        sheet.style.removeProperty('--sheet-zoom');
      }
    }
    window.addEventListener('beforeprint', fitToPage);
    window.addEventListener('afterprint', resetZoom);
    return () => {
      window.removeEventListener('beforeprint', fitToPage);
      window.removeEventListener('afterprint', resetZoom);
    };
  }, [active]);

  return (
    <div className="view">
      <div className="page-head">
        <div>
          <h1>Templates</h1>
          <div className="sub">Generate blank, fill-in-the-blanks forms for case property & Malkhana registers, then print.</div>
        </div>
        <div className="btn-row">
          <button className="btn ghost" onClick={() => setShowBuilder(true)}>+ New Blank Form</button>
        </div>
      </div>

      {!active && (
        <div className="tmpl-grid">
          {formTemplates.map(t => (
            <div className="tmpl-card" key={t.id}>
              <div className="tmpl-card-name">{t.name}</div>
              <div className="tmpl-card-sub">{t.sub}</div>
              <div className="tmpl-card-meta">
                {t.hindi ? 'PERFORMA (HI)' : `${t.fields.length} FIELDS`}
              </div>
              <div className="tmpl-card-actions">
                <button className="btn small" onClick={() => setActive(t)}>Open</button>
              </div>
            </div>
          ))}
        </div>
      )}

      {active && (
        <div className="tmpl-preview">
          <div className="tmpl-preview-bar">
            <button className="btn ghost small" onClick={() => setActive(null)}>← All templates</button>
            <button
              className="btn small"
              onClick={() => window.print()}
            >🖨 Print blank form</button>
          </div>

          {/* Two-column: Fill details (left) | Template preview (right). */}
          <div className="tmpl-split">
            {/* LEFT — Fill details */}
            <div className="tmpl-fill-panel">
              <div className="tmpl-panel-head">Fill details</div>

              {/* Fill-from-FIR selector + per-field blanks. */}
              <div className="tmpl-fillbar">
                <label className="tmpl-fir-label">
                  Fill details from FIR / DD no.:
                  <select
                    value={selectedFir}
                    onChange={e => onFirChange(e.target.value)}
                    disabled={!cases.length}
                  >
                    <option value="">
                      {casesErr ? 'FIR list unavailable' : cases.length ? '— select —' : 'Loading FIRs…'}
                    </option>
                    {cases.map(c => (
                      <option key={c.id} value={c.id}>{c.id}</option>
                    ))}
                  </select>
                </label>
                {selectedFir && (
                  <span className="tmpl-fir-note">Prefilled from record · edit any field below</span>
                )}
              </div>

              <div className="tmpl-vals">
                {active.fields.map(f => (
                  <label key={f.key} className={`tmpl-val${f.type === 'textarea' ? ' ta' : ''}`}>
                    <span className="tmpl-val-label">
                      {f.label}
                      {f.hint && <em className="tmpl-hint"> ({f.hint})</em>}
                    </span>
                    {f.type === 'textarea'
                      ? <textarea
                          value={values[f.key] || ''}
                          onChange={e => onManual(f.key, e.target.value)}
                          placeholder="—"
                        />
                      : <input
                          type={f.type === 'date' ? 'date' : f.type === 'number' ? 'number' : 'text'}
                          value={values[f.key] || ''}
                          onChange={e => onManual(f.key, e.target.value)}
                          placeholder="—"
                        />}
                  </label>
                ))}
              </div>
            </div>

            {/* RIGHT — Template live preview */}
            <div className="tmpl-sheet-panel">
              <div className="tmpl-panel-head">Template (live preview)</div>
              <Sheet tmpl={active} values={values} />
            </div>
          </div>
        </div>
      )}

      {/* Custom blank-form builder */}
      <div className={`overlay${showBuilder ? ' open' : ''}`} onClick={e => {
        if (e.target === e.currentTarget) setShowBuilder(false);
      }}>
        <div className="form-card">
          <button type="button" className="tag-close" onClick={() => setShowBuilder(false)} aria-label="Close">✕</button>
          <h3>New Blank Form</h3>
          <div className="sub">Add your own field names — each becomes a blank fill-in line. Type one field per line.</div>
          <div className="form-grid">
            <label className="full">
              Document title
              <input
                value={docName}
                onChange={e => setDocName(e.target.value)}
                placeholder="e.g. Vehicle Seizure Form"
              />
            </label>
            <label className="full">
              Fields (one per line)
              <textarea
                value={fieldText}
                onChange={e => setFieldText(e.target.value)}
                placeholder={'FIR / DD No.\nDate\nVehicle No.\nEngine No.\nChassis No.\nSeized From'}
                style={{ minHeight: 140 }}
              />
            </label>
          </div>
          <div className="form-actions">
            <button type="button" className="btn ghost" onClick={() => setShowBuilder(false)}>Cancel</button>
            <button type="button" className="btn" disabled={!fieldText.trim()} onClick={build}>
              Create blank template
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
